---
- name: PULL REQUEST -- Update application repo
  hosts: localhost
  gather_facts: false
  tasks:

  - name: PULL REQUEST -- Check if repo exists locally
    ansible.builtin.stat:
      path: "/tmp/{{ event.repo_name }}"
    register: repo_stat

  - name: PULL REQUEST -- Clone application repository 
    ansible.builtin.git:
      repo: "{{ event.clone_url }}"
      dest: "/tmp/{{ event.repo_name }}"
      clone: true
      update: true
    when: repo_stat.stat.exists == false
    register: repo_cloned

  - name: PULL REQUEST -- Update application repository to event ref 
    ansible.builtin.git:
      repo: "{{ event.clone_url }}"
      dest: "/tmp/{{ event.repo_name }}"
      clone: true
      update: true
      version: "{{ event.gitref }}"
    register: repo_cloned

  - name: PULL REQUEST -- Comment on PR
    ansible.builtin.uri:
      url: http://podman:3000/api/v1/repos/{{ event.author }}/{{ event.repo_name }}/issues/{{ event.pr_id }}/comments
      user: student
      password: learn_ansible
      method: POST
      headers:
        Sudo: ansible
        Content-Type: application/json
        accept: application/json
      body:
        body: |
          Calling application deployment

          Event type: {{ event.type }}
          Branch: {{ event.gitref }}
          Author: {{ event.author }}
      force_basic_auth: yes
      status_code: 201
      body_format: json
    register: comment

  - set_fact:
      cacheable: true
      repo_stat: "{{ repo_stat }}"
      cloned: "{{ repo_cloned }}"
      etype: "{{ event.type }}"
      erepo: "{{ event.repo_name }}"
      eref: "{{ event.gitref }}"
      eauthor: "{{ event.author }}"
      comment: "{{ comment }}"
